version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "todo-list-aws"
#s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-upt09go84tay"
s3_prefix = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"default\""
image_repositories = []
confirm_changeset = false
resolve_s3 = true
fail_on_empty_changeset=false

[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "todo-list-aws-staging"
#s3_bucket = "aws-sam-cli-managed-staging-samclisourcebucket-upt09go84tay"
s3_prefix = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"staging\""
image_repositories = []
confirm_changeset = false
resolve_s3 = true
fail_on_empty_changeset=false

[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "todo-list-aws-production"
#s3_bucket = "aws-sam-cli-managed-production-samclisourcebucket-upt09go84tay"
s3_prefix = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"production\""
image_repositories = []
confirm_changeset = false
resolve_s3 = true
fail_on_empty_changeset=false
